language: ruby

env:
  - RUN_COVERAGE_REPORT=true

rvm:
  - 2.4.3
  - 2.5.3
  - 2.6.0

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
  - gem install bundler
  - bundle update --bundler
  - bundle update simplecov
  - bundle install --path vendor/bundle

# uncomment this line if your project needs to run something other than `rake`:
script:
  - bundle exec rspec spec
  - bundle exec rubocop

gemfile:
  - gemfiles/activesupport_3.gemfile
  - gemfiles/activesupport_4.gemfile
  - gemfiles/activesupport_5.gemfile

matrix:
  exclude:
  - rvm: 2.1.8
    gemfile: gemfiles/activesupport_5.gemfile
  - rvm: 2.2.2
    gemfile: gemfiles/activesupport_5.gemfile
